//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client1.HelloServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mycompany.com/2012/11", ConfigurationName="HelloServiceProxy.HelloServiceContract")]
    public interface HelloServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/2012/11/HelloServiceContract/MyHelloMessage", ReplyAction="http://www.mycompany.com/2012/11/HelloServiceContract/MyHelloMessageResponse")]
        string MyHelloMessage(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/2012/11/HelloServiceContract/MyHelloMessage", ReplyAction="http://www.mycompany.com/2012/11/HelloServiceContract/MyHelloMessageResponse")]
        System.Threading.Tasks.Task<string> MyHelloMessageAsync(string firstName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloServiceContractChannel : Client1.HelloServiceProxy.HelloServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceContractClient : System.ServiceModel.ClientBase<Client1.HelloServiceProxy.HelloServiceContract>, Client1.HelloServiceProxy.HelloServiceContract {
        
        public HelloServiceContractClient() {
        }
        
        public HelloServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MyHelloMessage(string firstName) {
            return base.Channel.MyHelloMessage(firstName);
        }
        
        public System.Threading.Tasks.Task<string> MyHelloMessageAsync(string firstName) {
            return base.Channel.MyHelloMessageAsync(firstName);
        }
    }
}
